= Test-Plan

Dieser Testplan stellt eine vereinfachte Version der IEEE 829-1998 Vorlage dar.

== Einführung
Dieses Dokument soll einen Überblick über den Testablauf für das Softwaretechnologie Praktikum
bereitstellen. Zur Zielgruppe gehören Entwickler und Benutzer des Systems.

== Aufbau der Testbezeichner
Die Tests wurden analog zu den zugehörigen Use Cases von UC0010 bis UC0420 benannt.

== Test Gegenstände
=== Controller
- ApiCatalogController
- CatalogController
- EmployeeController
- InventoryController
- OrderController
- UserController

=== Entitäten
- Company
- Employee
- Inventory
- Item
- Personal
- User

=== Sonstige
- MampfCatalog
- RegistrationForm
- MampfOrder
- UserManagement

== Zu testende Funktionalitäten
- Inventar betrachten
- Catalog betrachten
-

== Nicht zu testende Funktionalitäten
- Spring Boot
- Spring MVC
- Thymleaf
- Salespoint Framework
- H2 Database

== Herangehensweise
1. Die Getter und Setter-Methoden der Klassen werden getestet.
2. Überprüfung von Grundfunktionen bei Controllern
3. Integrationstest nach Bottom-Up Prinzip

== Umgebungsvoraussetzungen
Die Umgebungsvorraussetzungen lassen sich in folgende Kategorien aufteilen.

=== Benötigte Hardware:
- Maus
- Tastatur
- Computer
- Monitor
- Netzwerkgeräte

=== Software für Tests und Codeanalyse:
- JUnit
- Jenkins
- SonarCube

=== Kommunikation während des Testens:
- lokal mit dem Dev-Server auf localhost:8080 über HTTP

== Testfälle und Verantwortlichkeit
Jede testbezogene Aufgabe muss einem Ansprechpartner zugeordnet werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|…  |**<<UC0010>>** |Benutzer ist nicht angemeldet|Anmeldedaten (Nutzername, Passwort)
|Startseite (Erfolg) / Login Seite (falsches Passwort/Benutzername)
|…|**<<UC0020>>**|Benutzer ist nicht angemeldet|Daten für ein neues Benutzerkonto: Benutzername, Vor- und Nachname, Passwort,
Adresse, Typ des Benutzerzugangs, E-Mail, Firmenname (nur bei Company), AccessCode (nur bei Employee)|
Startseite (Erfolg) / Registrierungsseite mit Fehlermeldung (ein Konto mit diesem Benutzernamen existiert bereits)
|…|**<<UC0100>>**|keine|Der Benutzer klickt im Menu auf das Element "Katalog"|Katalogseite
|…|**<<UC0101>>**|Benutzer ist angemeldet, hat die Rolle "BOSS", klickt im Menu auf "Katalog"|
Benutzer klickt auf "hinzufügen".|Katalogseite mit neuem Katalogeintrag
|…|**<<UC0102>>**|Benutzer ist angemeldet, hat die Rolle "BOSS", klickt im Menu auf "Katalog"|
Benutzer klickt auf "bearbeiten"|Katalogseite mit bearbeitetem Katalogeintrag
|…|**<<UC0103>>**|Benutzer ist angemeldet, hat die Rolle "BOSS", klickt im Menu auf "Katalog"|
Benutzer klickt auf "entfernen"|Katalogseite ohne dem entsprechenden Katalogeintrag
|…|**<<UC0110>>**|Benutzer klickt im Menu auf "Katalog"|Benutzer klickt beim entsprechenden Produkt auf mehr anzeigen|
Es erscheint mehr Text beim angeklickten Katalogeintrag
|…|**<<UC0200>>**|Benutzer ist angemeldet|klick auf das blaue Plus rechts neben dem entsprechenden Katalogeintrag,
Zum Warenkorb hinzufügen| Warenkorbseite
|…|**<<UC0202>>**|Benutzer ist angemeldet|Benutzer klickt im Menu auf "Warenkorb"|Warenkorbseite
|…|**<<UC0210>>**|Benutzer ist angemeldet und befindet sich im Warenkorb|Benutzer klickt im "Warenkorb" auf "Leeren"|
Warenkorbseite ohne Artikel
|…|**<<UC0220>>**|Der angemeldete Benutzer hat die Rolle "CUSTOMER" im Programm. Der Warenkorb ist nicht leer.|
Kunde klickt auf "Kaufen".| Warenkorbseite
|…|**<<UC0243>>**|Der angemeldete Benutzer hat die Rolle "CUSTOMER" im Programm.
Der Kunde hat bereits eine Bestellung aufgegeben.|Kunde klickt im Menu auf "meine Bestellungen"|Bestellübersicht
|…|**<<UC0400>>**|Der angemeldete Benutzer hat die Rolle "CUSTOMER" im Programm.
Ein Kunde hat bereits eine Bestellung aufgegeben.
Der Kunde klickt in der Ansicht "meine Bestellungen" auf eine bestimmte Bestellung.|
Der Kunde klickt im Menu auf "Bestellungen".|Rechnung
|…|**<<UC0300>>**| Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.
Es hat sich bereits mindestens ein Kunde registriert.|Admin klickt im Menu auf "Kunden".|
Dem Administrator werden alle Kunden angezeigt.
|…|**<<UC0301>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.
Es hat sich bereits mindestens ein Kunde registriert.Der Admin klickt im Menu auf "Kunden".|
Admin klickt im Menu "Kunden" auf "Kunde löschen".| aktualisierte Liste aller Kunden
|…|**<<UC0310>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.
Es wurde bereits von mindestens einem Kunden eine Bestellung aufgegeben.|Der Admin klickt im Menu auf "Bestellungen".|
Dem Administrator werden alle Bestellungen angezeigt.
|…|**<<UC0320>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.|
Der Admin klickt im Menu auf "Inventar".|Dem Administrator wird das Inventar mit allen verfügbaren Ressourcen angezeigt.
|…|**<<UC0330>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.|Der Admin klickt im Menu auf "Personal".|
Dem Administrator wird die Zuteilung des Personals zu allen Bestellungen angezeigt.
|…|**<<UC0331>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.
Der Admin klickt im Menu auf "Bestellungen".|Der Admin klickt im Menu "Bestellungen" auf eine bestimmte Bestellung.|
Dem Administrator erhält die Möglichkeit, sein Personal dieser Bestellung zuzuteilen.
|…|**<<UC0341>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.
|Der Admin klickt im Menu auf "Mitarbeiter".Dort kann er nach Personal filtern.|
Dem Admin wird sein gesamtes angestelltes Personal angezeigt .
|…|**<<UC0342>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.|
Der Admin klickt im Menu auf "Mitarbeiter". Dort klickt er auf "neues Personal einstellen".|
Dem Administrator erhält die Möglichkeit, den Namen des neuen Personals einzugeben
|…|**<<UC0344>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.Der Admin klickt im Menu auf "Mitarbeiter".
|Der Admin klickt im Menu "Mitarbeiter" für einen bestimmten Mitarbeiter auf den Button "löschen" bzw "bearbeiten".
|Dem Administrator wird die aktualisierte Liste seiner Mitarbeiter angezeigt.
|…|**<<UC0420>>**|Der angemeldete Benutzer hat die Rolle "ADMIN" im Programm.Der Admin klickt im Menu auf "Umsätze".|
Der Admin klickt im Menu "Umsätze" auf einen der angezeigten Monate.|
Dem Administrator werden alle Umsätze des jeweiligen Monats angezeigt.
|===
