image:https://github.com/st-tu-dresden-praktikum/swt20w10/workflows/CI%20build/badge.svg["CI Build", link="https://github.com/st-tu-dresden-praktikum/swt20w10/actions"]
image:https://img.shields.io/badge/SonarQube-checked-blue?logo=sonarqube["SonarQube status", link="https://st-lab-ci.inf.tu-dresden.de/sonarqube/"]

= Mampf :fries:

Mampf ist ein Eventcateringservice des Inhabers Hannes Mampf und stellt Dienste wie ein Eventcatering, Partyservice, Mobile-Breakfast und Rent-A-Cook zur Verfügung. Diese Repository hält die Verwaltungssoftware für alle diese Dienste, sowie Kunden und Mitarbeiterverwaltung.

== Wichtige Dokumente dieser Repository

* link:src/main/asciidoc/protocols[Meeting Protokolle]
* link:src/main/asciidoc/time_recording.adoc[Time recording (Zeiterfassung)]
* link:src/main/asciidoc/pflichtenheft.adoc[Requirements specification (Pflichtenheft)]
* link:src/main/asciidoc/developer_documentation.adoc[Developer documentation (Entwicklerdokumentation)]

== Das Repository-Layout

Diese Repository nutzt den typischen Aufbau eines Maven-Projects. Wie üblich werden alle anwendungsrelevanten Dateien in einem `src/` Ordner zusammengefasst:

  src/
  ├── main/
  │   ├── asciidoc/   -- Documentation of the development process and application (Asciidoc format)
  │   ├── java/       -- Main source code of the application, separated into packages
  │   └── resources/  -- Static assets (images, stylesheets), Thymeleaf templates, etc.
  └── test/
      └── java/       -- Source code of JUnit tests is stored separately

**Pro tip:** In GitHub, press *t* and a "fuzzy file finder" will appear, making it easy to navigate to a file.

== Um die Anwendung zu starten

* In der IDE: `Application.java` finden, Rechtsklick -> project, select "Run As > Java Application"
* `./mvnw spring-boot:run` im Terminal ausführen

==== VSCode

* Kommandofenster mit `F1` öffnen
* `Debug: Open launch.json` eingeben
* `Java` auswählen
* `launch.json` speichern
* `F5` benutzen um einen der beiden Debug-Tasks auszuwählen (der Zweite startet die ganze App)

== Erstellen eines Builds

* `cd <Pfad zum Entwicklungsordner>`
* `./mvnw clean package` ausführen
* Ein Build wird im Verzeichnis `target/` erstellt 
* Anwendung ausführen mit `java -jar $jarName`
