= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2020/21
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Florian Hauptmann

**Gruppe:** 10

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
* Negativ war für mich vor allem die fehlende Kommunikation von Angesicht zu Angesicht, was den Analyse- und Implementierungsprozess 
erschwert hat.
* Negative Erfahrungen habe ich außerdem mit UML-Programmen gemacht, darunter StarUML und VisualParadigm, die sich als sehr unübersichtlich herausstellten. Außerdem sehe ich nach dem Praktikum keinen Nutzen in der Erstellung von Klassendiagrammen, um innerhalb des Teams zu kommunizieren. Das Meiste konnte durch Sourcecode bereits verdeutlicht und erklärt werden, welches in der gleichen bis weniger Zeit geschrieben wurde als die Erstellung und Formatierung des jeweiligen Klassendiagramms gedauert hat.
* Mir ist zu Beginn die Mischung aus agiler Softwaremethode (Scrum) und dem Wasserfall-Prinzip sehr schwergefallen, da ich nicht den Eindruck gewann, dass Scrum als Methode dieses Praktikum maßgeblich verbessern würde. Ich hatte bereits die Möglichkeit in diversen Unternehmen Scrum als auch Kanban kennen zu lernen, als auch das Wasserfallmodell. Beides miteinander zu verknüpfen erscheint mir auch nach dem Projekt als wenig praktikabel. Dabei geht es mir vorallem um das Agile Manifest, was beispielsweise in seinen vier Werten in Punkt Zwei besagt, dass funktionsfähige Produkte vorrang vor detailierter Dokumentation haben, was im Praktikum anders gehandhabt wurde, was für mich aber ein wesentlicher Bestandteil von Scrum ist, um eine Methode überhaupt Scrum bzw. agil nennen zu können. Dazu kommt, dass das Backlog in der Agilen Softwareentwicklung als Ersatz für das Pflichtenheft steht, in dem man Userstories nur dann aus Epics erstellt, wenn geplant ist, sie in Sprints näherer Zukunft in Tasks, also Aufgaben die in der Regel nicht länger dauern als einen Arbeitstag, abzuarbeiten. Respektive bedeutet das für mich, die Anwendung nicht im voraus komplett zu überblicken und alle Use-Cases aufzustellen, die die Anwendung benötigt oder benötigen könnte (Muss- und Kann-Kriterien), sondern in erster Linie das Minimal-Valuelable-Product im Blick zu haben und nur dessen Muss-Kriterien zu erfüllen, um danach wieder Muss-Kriterien für den nächsten Zyklus zu planen.
Meine Auffassung und Erfahrung von agiler Softwareentwicklung in Kombination mit der, im Praktikum geforderten, Entwicklungsmethode hat mir es es erschwert zu begreifen, welchen Mehrwert die Implementierung von Scrum im Praktikum hat und mich zu dem Schluss kommen lassen, dass ein einfaches Wasserfallmodell für die Umsetzung wahrscheinlich für mich besser gewesen wäre. 
Das implmentieren von Zyklen, in denen jemand prüft, ob vorgenommene Aufgaben erfüllt wurden hat für mich auch nach wie vor wenig mit Scrum zu tun.
* Mir ist im Praktikum klar geworden, dass man vor allem als Softwareentwickler über den Tellerand hinausschauen und sich nicht von bereits vorhandenen Kenntnissen vereinamen lassen sollte. Die Gefahr einer Berufsblindheit wurde mir vorallem durch die Restriktion der Benutzung von JavaScript und dem Zwang der Benutzung von Spring und Salespoint verdeutlicht. Bevor ich Spring kennen lernen durfte habe ich vorrangig mit C#, JavaScript und PHP und deren Frameworks, namentlich ASP.Net, Express und Laravel gearbeitet. Ich war überrascht über die Features, Einfachheit und Sicherheit, die Spring einem Entwickler von Haus aus bietet. In den meisten anderen Fällen muss man selbst tätig werden, um so viele Sicherheitsrisiken aus dem Weg zu räumen, wie es bei Spring der Fall ist oder noch mehr Bibliotheken einbinden, was bei Spring intial alles schon dabei ist. Diese Erfahrung im Hinblick auf meine Ursprüngliche Einstellung zu Java, die in keinster weise positiv war, hat mir gezeigt, dass man sich eher über das große Ganze gedanken machen sollte als sich an einer Sprache und deren Struktur festzuhalten.
Außerdem war ich gezwungen, mich viel mehr mit HTML5 und CSS und deren Funktionen auseinanderzusetzen als auch die Nachteile von JavaScript näher zu beleuchten. Ich habe gelernt, dass nicht alles was gerade Trend ist, besser ist bzw. keine neuen Probleme mit sich bringt. Die übermäßige Menge an Daten die man downloaden muss, durch die Menge an JavaScript in einer Single-Page-Appplication, nur um Informationen anzuzeigen, obwohl man dazu nur eine simple und "leichte" HTML-Datei bräuchte, um nur ein Beispiel zu nennen.

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
* Ich habe die Erfahrung gemacht, dass Kommunikation das A und O im Teamwork ist. Leider wurde relativ wenig kommuniziert bzw. gab es keinen regen Meinungsaustausch, wie ich es anfangs erwartet hatte. Trotzdem würde ich die Arbeit mit den anderen als sehr positiv beschreiben. Dazu waren alle sehr eifrig ab einem gewissen Punkt.
* Mir hat besonders der Austausch und das von einander Lernen gefallen.
* Ich hätte sehr gerne mit meinen Teammitgliedern mehr Code-Review durchgeführt, da zum einen man seinen eigenen Code reflektiert und verbessern kann, als auch andere dabei unterstützen könnte, was sich für mich nach dem Praktikum als notwendig herausstellt.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
* Wie bereits oben beschrieben, war ich sehr überrascht von der Arbeit mit Spring. Beispielsweise ist das Verknüpfen von Klassen mit Controllern sehr einfach und geht gut von der Hand. Parameter Injection ist meiner Meinung nach ein Feature, was ich in vielen anderen Anwenungen gebraucht hätte und auch übersichticher ist als ein "globaler Kontext" bzw. Data-Hooks, Properties und State, wie es viele JavaScript-Frameworks und Bilbiotheken umsetzen.
* Auch die Benutzung und Implementation des ORM-Framework Hibernate hat mir sehr gefallen und mich überrascht wie einfach alles funtkioniert.
* Salespoint hat mir nur bedingt geholfen. Natürlich hat es uns bspw. die Arbeit mit JPA-Repositories erspart oder die grundlegende Implementierung von einem Warenkorb oder Zahlungsmethoden, jedoch finde ich es auch zu restriktiv. Natürlich könnte man sagen, dass man sich etwas bei der Restriktion gedacht habe, was aber nicht den Fakt schmälert, dass diese Restriktion einen meiner Teamkollegen dazu gebracht hat die Klasse OrderManagement als Attribut in einer anderen Klasse namens MampfOrderManager zu implementieren, um zusätzliche Funktionen zu etablieren, was ich eher als Workaround betrachte als eine gute Lösung. Ich wende mich eher ab von Frameworks, die mir die Entwicklung erleichtern sollten, mir dabei aber trotzdem Steine in den Weg legen.
* Ein anderes Problem, dass ich mit Salepoint habe ist, die Umständlichkeit des Änderns von Werten der "UniqueInventoryItems". Wann auch immer ich einen Wert eines Items ändern will, also beispielsweise seine Quantität oder den Preis, muss ich diesen Eintrag aus der Repository löschen und einen neuen hinzufügen, wobei dann noch das Kopieren der nicht zu verändernden Werte vom alten Eintrag auf den Neuen von Nöten ist. Das halte ich für sehr umständlich und unnötig, da man einfach eine Methode für das Verändern dieser Werte hätte hinzufügen können. Will man das trotzdem erreichen muss man die schon vorhandene Funktionalitäten opfern und diese Werte in einer neuen Klasse überschreiben.


== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
* Ich würde es begrüßen, wenn man sich lediglich auf die Benutzung des Wasserfall-Prinzips als Entwicklungsmethode beschränkt, da Studenten bei ihrem Eintritt in das Berufsleben eventuell eher mit Agiler Softwareentwicklung in Berührung kommen, als mit tradionellen Methoden, wenn man nach den Ergebnissen der "State of Agile Survey" geht. Ich halte es aber für durchaus wichtig auch tradionelle Methoden kennen zu lernen, vor allem wie sich ursprünglich angedacht waren. Nicht jedes Projekt erfordert Agilität und viele sind sich nicht mal im Klaren, was das genau bedeutet, bedingt durch die inflationäre Benutzung dieses Begriffs. Ich halte beispielsweise dieses Praktikum, wie es dieses Semester umgesetzt werden musste, für ein gutes Beispiel, das traditionelle Methoden besser geeignet sind als Agile. Auch bei der Entwicklung von Embedded-Systems oder der Arbeit in einer Entwicklungsabteilung einer Firma, die kein StartUp ist und bei der es keine Rolle spielt, wie schnell ein Produkt auf dem Markt erscheinen muss, halte ich Agile Softwareentwicklung als nicht geeignet. Daher komme ich zu dem Schluss, dass es vorteilhaft ist, solche Methoden kennen zu lernen, da die Wahrscheinlichkeit besteht, dass man sie in einem industriellen Kontext nicht lernt.
* Außerdem fände ich es wünschenswert, wenn man einen Einführungskurs in die Webentwicklung und die grundlegenden Funktionalitäten des Internets geben könnte. Mir ist bei der Arbeit mit meinen Teamkollegen aufgefallen, dass teilweise kein Vorwissen besteht über das HTTP-Protokoll, Websecurity und HTML, um nur einige Beispiele zu nennen. Man kann natürlich auch selbstverständlich erwarten, dass ein Student in der Lage ist sich derartige Grundlagen selbst anzueigenen, aber ich fände es dennoch wünschenswert, da es die Zusammenarbeit erleichtern würde, mit denen die sich bereits damit auseinandergesetzt haben.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
* Ich war mit dem Tutor äußerst zufrieden. Sehr zuverlässig, freundlich, sachlich aber auch notwendigerweise streng. Außerdem wurde sich sehr bemüht etwaige technische Fragen schnellstmöglich zu beantworten. Dazu konnte man den Tutor gefühlt Tag und Nacht erreichen, wenn es ein Problem gab. Auch Diskussionen haben mit dem Tutor sehr viel Spaß gemacht, auch wenn sie nur von kurzer Dauer waren.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
* Mir hat das Praktikum eine Menge Spaß bereitet und war bisher in meinem gesamten Studium auf jeden Fall das Highlight. Auch die Zusammenarbeit mit meinen Kommolitonen, war ein Lichtblick während der gesamten Coronazeit, die dieses Praktikum überschattete.

